In [1]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_iris

In [3]:
irisData = load_iris()

In [4]:
X = irisData.data
print(X[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [5]:
Y = irisData.target
print(Y[:5])

[0 0 0 0 0]


In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=45)

In [7]:
from sklearn.ensemble import AdaBoostClassifier
Ada_Cls = AdaBoostClassifier()

In [8]:
AdaBoostClassifier?

In [9]:
Ada_Cls.fit(X_test, y_test)

AdaBoostClassifier()

In [10]:
y_pre = Ada_Cls.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, y_pre)
acc

1.0

In [12]:
from sklearn.linear_model import LogisticRegression
Ada_Cls1 = AdaBoostClassifier(base_estimator=LogisticRegression())

In [13]:
Ada_Cls1.fit(X_test,y_test)

AdaBoostClassifier(base_estimator=LogisticRegression())

In [14]:
y_pre1 = Ada_Cls1.predict(X_test)

In [15]:
acc1 = accuracy_score(y_test,y_pre1)
acc1

0.8666666666666667

In [19]:
from sklearn.svm import SVC

In [21]:
Ada_Cls2 = AdaBoostClassifier(base_estimator=SVC(probability=True,kernel='linear'))
Ada_Cls2.fit(X_train,y_train)

AdaBoostClassifier(base_estimator=SVC(kernel='linear', probability=True))

In [22]:
y_pre2 = Ada_Cls2.predict(X_test)

In [23]:
acc2 = accuracy_score(y_test,y_pre2)
acc2

0.9333333333333333