In [1]:
import pandas as pd
import numpy as np
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('D:\CDAC\ML\car_evaluation.csv', header=None)

In [7]:
df.head(5)

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [8]:
df.shape

(1728, 7)

In [9]:
df.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

In [10]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1723    False
1724    False
1725    False
1726    False
1727    False
Length: 1728, dtype: bool

In [11]:
df.duplicated().sum()

0

In [13]:
df.columns

Int64Index([0, 1, 2, 3, 4, 5, 6], dtype='int64')

In [14]:
cols = ['features 1','features 2','features 3','features 4','features 5','features 6','target']

In [15]:
df.columns =cols

In [16]:
df.columns

Index(['features 1', 'features 2', 'features 3', 'features 4', 'features 5',
       'features 6', 'target'],
      dtype='object')

In [17]:
df['features 1'].unique()

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [18]:
df['features 1']=df['features 1'].map({'vhigh':1,'high':2,'med':3,'low':4})

In [19]:
df['features 1'].unique()

array([1, 2, 3, 4], dtype=int64)

In [20]:
df['features 2'].unique()

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [21]:
df['features 2']=df['features 2'].map({'vhigh':1,'high':2,'med':3,'low':4})

In [22]:
df['features 3'].unique()

array(['2', '3', '4', '5more'], dtype=object)

In [23]:
df['features 3']=df['features 3'].str.replace('5more','6')

In [24]:
df['features 3'].unique()

array(['2', '3', '4', '6'], dtype=object)

In [25]:
df['features 4'].unique()

array(['2', '4', 'more'], dtype=object)

In [26]:
df['features 4']=df['features 4'].str.replace('more','6')

In [27]:
df['features 4'].unique()

array(['2', '4', '6'], dtype=object)

In [28]:
df['features 5'].unique()

array(['small', 'med', 'big'], dtype=object)

In [29]:
df['features 5']=df['features 5'].map({'small':1,'med':2,'big':3})

In [30]:
df['features 5'].unique()

array([1, 2, 3], dtype=int64)

In [31]:
df['features 6'].unique()

array(['low', 'med', 'high'], dtype=object)

In [32]:
df['features 6']=df['features 6'].map({'low':1,'med':2,'high':3})

In [33]:
df['target'].unique()

array(['unacc', 'acc', 'vgood', 'good'], dtype=object)

In [34]:
df['target']=df['target'].map({'unacc':1,'acc':2,'vgood':3,'good':4})

In [35]:
df['target'].unique()

array([1, 2, 3, 4], dtype=int64)

In [36]:
df.head(5)

features 1  features 2 features 3 features 4  features 5  features 6  \
0           1           1          2          2           1           1   
1           1           1          2          2           1           2   
2           1           1          2          2           1           3   
3           1           1          2          2           2           1   
4           1           1          2          2           2           2   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [39]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [40]:
x

features 1  features 2 features 3 features 4  features 5  features 6
0              1           1          2          2           1           1
1              1           1          2          2           1           2
2              1           1          2          2           1           3
3              1           1          2          2           2           1
4              1           1          2          2           2           2
...          ...         ...        ...        ...         ...         ...
1723           4           4          6          6           2           2
1724           4           4          6          6           2           3
1725           4           4          6          6           3           1
1726           4           4          6          6           3           2
1727           4           4          6          6           3           3

[1728 rows x 6 columns]

In [41]:
y

0       1
1       1
2       1
3       1
4       1
       ..
1723    4
1724    3
1725    1
1726    4
1727    3
Name: target, Length: 1728, dtype: int64

In [42]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=34)

In [43]:
dt = DecisionTreeClassifier(criterion = 'entropy')
dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [44]:
y_pred = dt.predict(x_test)

In [45]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9710982658959537
