In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [2]:
irisData = load_iris()

In [3]:
irisData.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
X = irisData.data
print(X[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [5]:
y = irisData.target
print(y[:5])

[0 0 0 0 0]


In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=45)

In [11]:
from sklearn.ensemble import GradientBoostingClassifier
GB_cls = GradientBoostingClassifier()

In [12]:
GB_cls.fit(X_test,y_test)

GradientBoostingClassifier()

In [14]:
y_pre = GB_cls.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,y_pre)
acc

1.0

In [16]:
GradientBoostingClassifier?