In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv("D:\\CDAC\\Github\\Machine_Learning_Tutorials\\Linear_Regression\\homeprice.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [5]:
model.coef_

array([135.78767123])

In [6]:
model.intercept_

180616.43835616432

In [7]:
model.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

# Save Model To a File Using Python Pickle

In [8]:
import pickle

In [9]:
with open('model.pickle','wb') as file:
    pickle.dump(model,file)

# Load Saved Model

In [10]:
with open('model.pickle','rb') as file:
    mp = pickle.load(file)

In [11]:
mp.coef_

array([135.78767123])

In [12]:
mp.intercept_

180616.43835616432

In [13]:
mp.predict([[4500]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([791660.95890411])